#! /bin/bash

if [ -z "$1" ]; then
  git fetch &&
    git checkout master
else
  if [ -z "$2" ]; then 
    git fetch origin $1 &&
      git checkout $1
  else
    git fetch $2 $1 &&
      git checkout $2/$1
  fi
fi
